import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  AlarmClockIcon,
  ArrowDataTransferHorizontalIcon,
  Archive02Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowTurnBackwardIcon,
  ArrowUp01Icon,
  ArrowUpRight01Icon,
  Atom01Icon,
  Bookmark02Icon,
  BotIcon,
  BrainIcon,
  Briefcase01Icon,
  Calendar01Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  Clock01Icon,
  CodeIcon,
  CompassIcon,
  ComputerTerminal01Icon,
  Copy01Icon,
  CrownIcon,
  CubeIcon,
  Delete02Icon,
  DiamondIcon,
  Edit02Icon,
  FileText,
  FireIcon,
  Flag02Icon,
  FloppyDiskIcon,
  FolderIcon,
  FolderOpenIcon,
  GemIcon,
  GitPullRequestIcon,
  Globe02Icon,
  HelpCircleIcon,
  Home01Icon,
  InboxIcon,
  InformationCircleIcon,
  KanbanIcon,
  Leaf01Icon,
  LayoutTwoColumnIcon,
  Loading03Icon,
  Mail01Icon,
  MailOpen01Icon,
  MoonIcon,
  MoreHorizontalIcon,
  Notification01Icon,
  PackageIcon,
  PauseIcon,
  PencilEdit01Icon,
  PinIcon,
  PinOffIcon,
  PlayIcon,
  PlusSignIcon,
  PuzzleIcon,
  RefreshIcon,
  RepeatIcon,
  RocketIcon,
  RssIcon,
  Search01Icon,
  SentIcon,
  Settings01Icon,
  ShieldIcon,
  SparklesIcon,
  StarIcon,
  Sun01Icon,
  Target02Icon,
  TelescopeIcon,
  Tick02Icon,
  Trophy,
  UserAdd01Icon,
  UserGroupIcon,
  WorkflowCircle03Icon,
  WrenchIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons";
import { cn } from "../../lib/utils";

const ICON_MAP = {
  AlarmClock: AlarmClockIcon,
  ArrowTurnBackward: ArrowTurnBackwardIcon,
  Atom: Atom01Icon,
  Bell: Notification01Icon,
  Bookmark: Bookmark02Icon,
  Bot: BotIcon,
  Brain: BrainIcon,
  Briefcase: Briefcase01Icon,
  Calendar: Calendar01Icon,
  Check: Tick02Icon,
  CheckCircle: CheckmarkCircle02Icon,
  ChevronDown: ArrowDown01Icon,
  ChevronLeft: ArrowLeft01Icon,
  ChevronRight: ArrowRight01Icon,
  ChevronUp: ArrowUp01Icon,
  CircleQuestion: HelpCircleIcon,
  CircleX: CancelCircleIcon,
  Clock: Clock01Icon,
  Code: CodeIcon,
  Compass: CompassIcon,
  Copy: Copy01Icon,
  Columns2: LayoutTwoColumnIcon,
  Crown: CrownIcon,
  Cube: CubeIcon,
  Delete: Delete02Icon,
  Diamond: DiamondIcon,
  Edit: Edit02Icon,
  ExternalLink: ArrowUpRight01Icon,
  FileText: FileText,
  Fire: FireIcon,
  Flag: Flag02Icon,
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  Gem: GemIcon,
  GitPullRequest: GitPullRequestIcon,
  Globe: Globe02Icon,
  Home: Home01Icon,
  Inbox: InboxIcon,
  Info: InformationCircleIcon,
  Kanban: KanbanIcon,
  Leaf: Leaf01Icon,
  ListTodo: CheckListIcon,
  Loading: Loading03Icon,
  Mail: Mail01Icon,
  MailOpen: MailOpen01Icon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  MoveTo: ArrowDataTransferHorizontalIcon,
  Package: PackageIcon,
  Pause: PauseIcon,
  Pencil: PencilEdit01Icon,
  Pin: PinIcon,
  PinOff: PinOffIcon,
  Play: PlayIcon,
  Plus: PlusSignIcon,
  Puzzle: PuzzleIcon,
  Refresh: RefreshIcon,
  Repeat: RepeatIcon,
  Rocket: RocketIcon,
  Rss: RssIcon,
  Save: FloppyDiskIcon,
  Search: Search01Icon,
  Send: SentIcon,
  Settings: Settings01Icon,
  Shield: ShieldIcon,
  Sparkles: SparklesIcon,
  Star: StarIcon,
  Sun: Sun01Icon,
  Target: Target02Icon,
  Telescope: TelescopeIcon,
  Terminal: ComputerTerminal01Icon,
  Trash: Archive02Icon,
  Trophy: Trophy,
  UserRoundPlus: UserAdd01Icon,
  Users: UserGroupIcon,
  Workflow: WorkflowCircle03Icon,
  Wrench: WrenchIcon,
  X: Cancel01Icon,
  Zap: ZapIcon,
} as const satisfies Record<string, IconSvgElement>;

export type IconName = keyof typeof ICON_MAP;

export function Icon({
  name,
  className,
  "aria-hidden": ariaHidden,
  "aria-label": ariaLabel,
}: {
  name: IconName;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
  "aria-label"?: string;
}) {
  return (
    <HugeiconsIcon
      icon={ICON_MAP[name]}
      className={cn(className)}
      aria-hidden={ariaHidden}
      aria-label={ariaLabel}
      data-icon={name}
    />
  );
}
