// The plugin's own Amp CLI spawn layer: execute-wire types, argv construction,
// the settings/mcp temp files, process lifecycle, and NDJSON in both
// directions. Written independently from observed CLI behavior; it copies no
// @ampcode/sdk code. `createAmpExecute` produces the `AmpExecuteFn` the
// conversation layer consumes, so everything above this module stays
// protocol-level.
import { spawn, type ChildProcess } from "node:child_process";
import { once } from "node:events";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { createInterface } from "node:readline";
import type { AmpExecutionTrace, AmpStartupCheckpoint } from "./telemetry.ts";

export type { AmpExecutionTrace } from "./telemetry.ts";

/** One `amp.permissions` entry. The plugin only ever rejects tools. */
export interface AmpPermissionRule {
  tool: string;
  action: "reject";
}

/** The `--mcp-config` document: server name to stdio launch spec. */
export type MCPConfig = Record<
  string,
  {
    command: string;
    args?: readonly string[];
    env?: Record<string, string>;
  }
>;

/** A stream-json stdin line. `steer` marks mid-turn injection. */
export interface AmpUserInputMessage {
  type: "user";
  message: {
    role: "user";
    content: Array<{ type: "text"; text: string }>;
  };
  steer?: true;
}

export interface AmpExecuteOptions {
  cwd?: string;
  mode?: string;
  thinking?: boolean;
  fast?: boolean;
  noArchiveAfterExecute?: boolean;
  dangerouslyAllowAll?: boolean;
  permissions?: readonly AmpPermissionRule[];
  labels?: readonly string[];
  mcpConfig?: MCPConfig;
  continue?: string;
  /** Local execution is the default and is expressed by omission. */
  executor?: "orb";
  project?: string;
  env?: Record<string, string>;
}

export type AmpExecutePrompt = string | AsyncIterable<AmpUserInputMessage>;

export type AmpExecuteFn = (args: {
  prompt: AmpExecutePrompt;
  signal?: AbortSignal;
  options?: AmpExecuteOptions;
  trace?: AmpExecutionTrace;
}) => AsyncIterable<unknown>;

export function createUserMessage(text: string): AmpUserInputMessage {
  return {
    type: "user",
    message: { role: "user", content: [{ type: "text", text }] },
  };
}

/** Which execute option produced a given optional CLI flag. The conversation
 *  layer's unsupported-flag retry uses this to drop exactly that option.
 *
 *  A flag belongs here only when dropping it loses a preference. Three
 *  absences are deliberate, because dropping those changes where the work
 *  runs or what it is allowed to do:
 *  - `--orb-execute`: a CLI that cannot run Orb must fail, not silently
 *    execute locally.
 *  - `--project`: dropping it does not pick a named default, it reverts to
 *    inferring the project from the working directory's git remotes. A user
 *    sets `orbProject` precisely to override that inference, so the retry
 *    would silently run the Orb thread against a different repository.
 *  - `--settings-file`: the file carries an explicit
 *    `amp.dangerouslyAllowAll: false` that overrides the user's persisted
 *    setting. Dropping the mapped option removes the file, so the CLI falls
 *    back to persisted settings and a user-level `true` takes effect. The
 *    flag is also generated by `permissions`, which one option cannot
 *    express, so the drop could not reliably stop it either way.
 *
 *  `--dangerously-allow-all` stays droppable: it is emitted only when the
 *  option is `true`, so dropping it can only remove permission.
 *  `--execute`/`--stream-json`/`--stream-json-input` are the wire itself. */
const DROPPABLE_FLAGS: Readonly<Record<string, keyof AmpExecuteOptions>> = {
  fast: "fast",
  "stream-json-thinking": "thinking",
  mode: "mode",
  "no-archive-after-execute": "noArchiveAfterExecute",
  "dangerously-allow-all": "dangerouslyAllowAll",
  "mcp-config": "mcpConfig",
  label: "labels",
};

export function optionForFlag(flag: string): keyof AmpExecuteOptions | null {
  return Object.hasOwn(DROPPABLE_FLAGS, flag) ? DROPPABLE_FLAGS[flag]! : null;
}

export interface AmpArgvPaths {
  settingsFile?: string;
  mcpConfigFile?: string;
}

/** The execute-wire argv, in the order the Amp CLI has always received it.
 *  Faithful to its inputs: the caller decides which temp files exist. Unlike
 *  the retired SDK driver it never defaults `--mode` — the conversation layer
 *  always sets one, and an unset option must stay droppable.
 *  `streamJsonInput` must mirror how the caller feeds stdin: without the
 *  flag the CLI reads stdin as raw prompt text until EOF, so framed input
 *  on a held-open stdin hits the CLI's 30s stdin read timeout. */
export function buildAmpArgv(
  options: AmpExecuteOptions,
  paths: AmpArgvPaths = {},
  streamJsonInput = false,
): string[] {
  const argv: string[] = [];
  if (options.continue !== undefined) argv.push("threads", "continue", options.continue);
  if (options.fast === true) argv.push("--fast");
  argv.push("--execute", options.thinking === true ? "--stream-json-thinking" : "--stream-json");
  if (streamJsonInput) argv.push("--stream-json-input");
  if (options.executor === "orb") {
    argv.push("--orb-execute");
    if (options.project !== undefined) argv.push("--project", options.project);
  }
  if (options.dangerouslyAllowAll === true) argv.push("--dangerously-allow-all");
  if (options.noArchiveAfterExecute === true) argv.push("--no-archive-after-execute");
  if (paths.settingsFile !== undefined) argv.push("--settings-file", paths.settingsFile);
  if (paths.mcpConfigFile !== undefined) argv.push("--mcp-config", paths.mcpConfigFile);
  if (options.mode !== undefined) argv.push("--mode", options.mode);
  for (const label of options.labels ?? []) argv.push("--label", label);
  return argv;
}

/** The `--settings-file` document: the user's own Amp settings with the two
 *  keys the plugin controls merged on top. `env` is the child's environment,
 *  so the settings the CLI would read are the settings we extend. */
export function buildAmpSettings(
  options: Pick<AmpExecuteOptions, "permissions" | "dangerouslyAllowAll">,
  env: Record<string, string | undefined>,
): Record<string, unknown> {
  const settings = loadBaseSettings(env);
  if (options.permissions !== undefined) settings["amp.permissions"] = [...options.permissions];
  if (options.dangerouslyAllowAll !== undefined) {
    settings["amp.dangerouslyAllowAll"] = options.dangerouslyAllowAll;
  }
  return settings;
}

function loadBaseSettings(env: Record<string, string | undefined>): Record<string, unknown> {
  const explicit = env.AMP_SETTINGS_FILE;
  if (explicit !== undefined && explicit.trim().length > 0) {
    // An explicitly named settings file that is missing or broken must fail
    // loudly; silently running without the user's settings is worse. A valid
    // JSON scalar or array is the same kind of broken: coercing it to {}
    // drops the whole document, including the explicit
    // `amp.dangerouslyAllowAll: false` bb writes there, so the turn would run
    // on the user's persisted setting instead of the one bb asked for.
    return requireSettingsObject(JSON.parse(readFileSync(explicit, "utf8")), explicit);
  }
  const xdg = env.XDG_CONFIG_HOME;
  const configHome = xdg !== undefined && xdg.trim().length > 0 ? xdg : join(homedir(), ".config");
  for (const name of ["settings.json", "settings.jsonc"]) {
    let raw: string;
    try {
      raw = readFileSync(join(configHome, "amp", name), "utf8");
    } catch {
      continue;
    }
    try {
      return asSettingsObject(JSON.parse(raw));
    } catch {
      // settings.jsonc with comments does not parse as JSON; the CLI's own
      // loader skipped unparseable candidates, and so do we.
      continue;
    }
  }
  return {};
}

function isSettingsObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Discovered settings files are best-effort: an unusable one is skipped, the
 *  way the CLI's own loader skips it. Throwing is how it is skipped, because
 *  the caller's `catch` moves to the next candidate. Returning {} instead
 *  ended the search on the unusable file and dropped the user's settings. */
function asSettingsObject(value: unknown): Record<string, unknown> {
  if (!isSettingsObject(value)) throw new Error("settings file is not a JSON object");
  return { ...value };
}

/** An explicitly named settings file is not best-effort. */
function requireSettingsObject(value: unknown, path: string): Record<string, unknown> {
  if (!isSettingsObject(value)) {
    throw new Error(`AMP_SETTINGS_FILE ${path} is not a JSON object`);
  }
  return { ...value };
}

/** Retained stderr is bounded. A long-lived execution can emit stderr for
 *  hours and every byte was kept until exit, which is a slow leak in a
 *  process that outlives many turns. The tail is the part failure reporting
 *  needs, and a startup failure (the path parseUnsupportedFlag reads) emits
 *  far less than this before the CLI exits. */
const STDERR_LIMIT = 64 * 1024;

export function appendBoundedStderr(text: string, chunk: string, limit = STDERR_LIMIT): string {
  const next = text + chunk;
  if (next.length <= limit) return next;
  return `[earlier stderr truncated]\n${next.slice(next.length - limit)}`;
}

export interface AmpExecuteDeps {
  /** Resolved Amp CLI path. `.js`/`.mjs`/`.cjs` entrypoints run through the
   *  current Node runtime, which is what lets tests substitute a script. */
  cliPath: string;
}

export function createAmpExecute(deps: AmpExecuteDeps): AmpExecuteFn {
  return ({ prompt, signal, options, trace }) =>
    runAmp(deps.cliPath, prompt, signal, options ?? {}, trace);
}

async function* runAmp(
  cliPath: string,
  prompt: AmpExecutePrompt,
  signal: AbortSignal | undefined,
  options: AmpExecuteOptions,
  trace: AmpExecutionTrace | undefined,
): AsyncGenerator<unknown, void, undefined> {
  signal?.throwIfAborted();
  const reported = new Set<string>();
  const checkpoint = (name: AmpStartupCheckpoint): void => {
    if (reported.has(name)) return;
    reported.add(name);
    trace?.checkpoint(name);
  };
  checkpoint("execute_entered");
  const env = { ...process.env, ...options.env };
  let tempDir: string | null = null;
  let child: ChildProcess | null = null;
  try {
    if (options.mcpConfig !== undefined && options.executor === "orb") {
      throw new Error("mcpConfig is not supported for Orb executions");
    }
    const paths: AmpArgvPaths = {};
    const needsSettings =
      options.permissions !== undefined || options.dangerouslyAllowAll !== undefined;
    if (needsSettings || options.mcpConfig !== undefined) {
      tempDir = mkdtempSync(join(tmpdir(), "bb-amp-"));
      if (needsSettings) {
        paths.settingsFile = join(tempDir, "settings.json");
        writeFileSync(paths.settingsFile, JSON.stringify(buildAmpSettings(options, env), null, 2), {
          mode: 0o600,
        });
      }
      if (options.mcpConfig !== undefined) {
        paths.mcpConfigFile = join(tempDir, "mcp-config.json");
        writeFileSync(paths.mcpConfigFile, JSON.stringify(options.mcpConfig), { mode: 0o600 });
      }
    }
    checkpoint("temp_files_ready");
    const argv = buildAmpArgv(options, paths, typeof prompt !== "string");
    const nodeScript = /\.(cjs|mjs|js)$/i.test(cliPath);
    checkpoint("spawn_called");
    child = spawn(nodeScript ? process.execPath : cliPath, nodeScript ? [cliPath, ...argv] : argv, {
      cwd: options.cwd ?? process.cwd(),
      env,
      stdio: ["pipe", "pipe", "pipe"],
      signal,
    });
    child.once("spawn", () => checkpoint("child_spawned"));
    let stderr = "";
    child.stderr!.setEncoding("utf8");
    child.stderr!.on("data", (chunk: string) => {
      stderr = appendBoundedStderr(stderr, chunk);
    });
    const exit = new Promise<number | null>((resolveExit, rejectExit) => {
      child!.once("error", rejectExit);
      child!.once("close", (code) => resolveExit(code));
    });
    // The consumer may abandon the generator before the exit is awaited.
    exit.catch(() => {});
    child.stdout!.once("data", () => checkpoint("first_stdout_byte"));
    pumpInput(child, prompt, signal, checkpoint);
    const lines = createInterface({ input: child.stdout!, crlfDelay: Infinity });
    for await (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.length === 0) continue;
      checkpoint("first_stdout_line");
      let message: unknown;
      try {
        message = JSON.parse(trimmed);
      } catch {
        console.error(`[amp] ignoring a non-JSON line from the Amp CLI: ${truncate(trimmed)}`);
        continue;
      }
      checkpoint("first_valid_json");
      yield message;
    }
    const code = await exit;
    checkpoint("process_closed");
    signal?.throwIfAborted();
    if (code !== 0) {
      // parseUnsupportedFlag reads the CLI's stderr out of this message, so
      // the stderr text must stay inside it.
      throw new Error(
        code === null
          ? `Amp CLI process was killed before exiting: ${stderr.trim()}`
          : `Amp CLI process exited with code ${code}: ${stderr.trim()}`,
      );
    }
  } finally {
    if (child !== null && child.exitCode === null && !child.killed) {
      child.kill(process.platform === "win32" ? "SIGKILL" : "SIGTERM");
    }
    if (tempDir !== null) rmSync(tempDir, { recursive: true, force: true });
  }
}

/** Feeds the prompt to the CLI's stdin without blocking the output reader.
 *  Messages are serialized as given — the steering `steer` flag rides along
 *  untouched. Stdin errors are swallowed locally (a dying CLI EPIPEs mid
 *  write); the exit-code check reports the real failure. */
function pumpInput(
  child: ChildProcess,
  prompt: AmpExecutePrompt,
  signal: AbortSignal | undefined,
  checkpoint: (name: AmpStartupCheckpoint) => void,
): void {
  const stdin = child.stdin;
  if (stdin === null) return;
  stdin.on("error", () => {});
  if (typeof prompt === "string") {
    stdin.write(prompt + "\n");
    checkpoint("input_written");
    stdin.end();
    return;
  }
  void (async () => {
    try {
      for await (const message of prompt) {
        if (signal?.aborted === true || stdin.destroyed || stdin.writableEnded) return;
        const accepted = stdin.write(JSON.stringify(message) + "\n");
        checkpoint("input_written");
        if (!accepted) {
          const settled = new AbortController();
          const drained = once(stdin, "drain", { signal: settled.signal }).catch(() => {});
          const closed = once(stdin, "close", { signal: settled.signal }).catch(() => {});
          await Promise.race([drained, closed]);
          settled.abort();
        }
      }
    } catch {
      // The input stream ends by throwing on abort; the reader owns errors.
    } finally {
      if (!stdin.destroyed) stdin.end();
    }
  })();
}

function truncate(line: string): string {
  return line.length > 200 ? `${line.slice(0, 200)}…` : line;
}
